[workspace]

resolver = "2"
members = ["update",
           "hal", 
           "firmware/*/*", 
           #"bootloaders/*"
           ]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
debug = true
lto = true
opt-level = 2
