[package]
name = "shakti"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shakti_riscv_hal = "0.1.2"
riscv-rt = "0.12"
riscv = "0.11"
embedded-hal = "1.0.0-alpha.8"


[workspace]